# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Member.create!([
  {name: "鈴木 綾子"},
  {name: "高橋 めぐみ"},
  {name: "田中 朋子"},
  {name: "鈴木 和美"},
  {name: "佐々木 真由美"},
  {name: "小林 真弓"},
  {name: "中村 千恵"},
  {name: "藤井 舞"},
  {name: "伊藤 千明"},
  {name: "松本 亜美"},
  {name: "鈴木 則子"},
  {name: "野口 瞳"},
  {name: "清水 弘子"},
  {name: "西田 由美"},
  {name: "増田 紀子"},
  {name: "中山 晶子"},
  {name: "関 恭子"},
  {name: "藤澤 恵"},
  {name: "斎藤 葵"},
  {name: "後藤 文子"},
  {name: "古田 仁美"},
  {name: "荒木 あかね"},
  {name: "渡辺 千代"},
  {name: "武田 絵梨"},
  {name: "星 博子"},
  {name: "松尾 麻実"},
  {name: "鷲尾 智子"},
  {name: "弓削 久美子"},
  {name: "野口 真貴子"},
  {name: "坂口 洋美	"},
  {name: "矢野 直樹"},
  {name: "佐藤 創"},
  {name: "伊藤 俊樹"},
  {name: "小林 勇介"},
  {name: "木下 祐介"},
  {name: "野田 祐介"},
  {name: "永井 真一"},
  {name: "長谷川 真一郎"},
  {name: "福島 渉"},
  {name: "堤 和彦"},
  {name: "古川 弘樹"},
  {name: "大西 昌弘"},
  {name: "杉浦 裕"},
  {name: "佐藤 洋二郎"},
  {name: "鈴木 昭徳"},
  {name: "野中 薫"},
  {name: "武内 浩二"},
  {name: "山本 暁"},
  {name: "村田 剛志"},
  {name: "佐藤 三千夫"},
  {name: "渡邉 竜"},
  {name: "高橋 寛司"},
  {name: "中村 紘一郎"},
  {name: "石原 剛史"},
  {name: "宮崎 崇史"},
  {name: "野口 優"},
  {name: "谷川 淳"},
  {name: "白石 雄大"},
  {name: "堀 正己"},
  {name: "山崎 広一	"},
])